services:
  - type: web
    name: slidecraft-ai-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn slidecraft_backend.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: slidecraft-ai-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-1.5-flash
      - key: GEMINI_MAX_TOKENS
        value: 8192
      - key: GEMINI_TEMPERATURE
        value: 0.7

databases:
  - name: slidecraft-ai-db
    databaseName: slidecraft_ai
    user: slidecraft_user
